"""
Auto-generated Manim script for: Heart Anatomy
Generated by EaseToLearn template_renderer.py — DO NOT EDIT MANUALLY
"""

import numpy as np
from manim import *

# ── LaTeX Template ─────────────────────────────────────────────────────────────
my_template = TexTemplate()
my_template.add_to_preamble(r"\usepackage{amsmath}")
my_template.add_to_preamble(r"\usepackage{amssymb}")

# ── 3Blue1Brown High-Fidelity Design System ──────────────────────────────────
class DesignTokens:
    BLUE   = "#58ADFF"
    GREEN  = "#77DD77"
    YELLOW = "#FFFF66"
    RED    = "#FF6666"
    PURPLE = "#C57AFF"
    WHITE  = "#FFFFFF"
    GRAY   = "#888888"
    BLACK  = "#000000"
    MAX_WIDTH = 12.0
    TITLE_SIZE = 1.4
    BODY_SIZE = 0.8
    SUBTITLE_SIZE = 0.7

config.background_color = DesignTokens.BLACK
config.pixel_height = 1080
config.pixel_width  = 1920

class EaseToLearnScene(Scene):

    def _clear(self):
        """Fade out all mobjects safely."""
        fos = [FadeOut(m) for m in self.mobjects]
        if fos:
            self.play(*fos)

    def _clear_keep_image(self):
        """Fade out all mobjects except background ImageMobject."""
        fos = [FadeOut(m) for m in self.mobjects if not isinstance(m, ImageMobject)]
        if fos:
            self.play(*fos)

    def construct(self):
        # Industrial 3b1b Canvas: Absolute Black
        # DesignTokens are available as a global class in this script.
        self.camera.background_color = DesignTokens.BLACK

        # Scene 0: title_card
        title_0 = Tex(r"\text{Cardiovascular Anatomy}", tex_template=my_template)
        title_0.scale(DesignTokens.TITLE_SIZE).set_color(DesignTokens.YELLOW).move_to(UP * 0.5)
        if title_0.width > DesignTokens.MAX_WIDTH: title_0.set_width(DesignTokens.MAX_WIDTH)

        self.play(Write(title_0), run_time=0.45)
        subtitle_0 = Tex(r"\text{The Internal Structures of the Heart}", tex_template=my_template)
        subtitle_0.scale(DesignTokens.SUBTITLE_SIZE).set_color(DesignTokens.BLUE).next_to(title_0, DOWN, buff=0.4)
        self.play(FadeIn(subtitle_0), run_time=0.9)
        self.wait(2.1)
        self.play(FadeOut(title_0), FadeOut(subtitle_0))


        # Scene 1: annotated_image
        self._clear()
        img_1 = ImageMobject(r"/Users/apple/Desktop/easetolearn.videogeneration/scratch/internal_heart_anatomy_diagram.png").scale_to_fit_width(5.5).move_to(RIGHT * 3.2)
        frame_1 = SurroundingRectangle(img_1, color=BLUE_E, buff=0.08, stroke_width=3)
        
        # Left side: explanation
        title_1 = Tex(r"\text{The Left Ventricle}", tex_template=my_template).scale(0.9).set_color(DesignTokens.YELLOW)
        
        bullets_grp_1 = VGroup(
            Tex(r"\text{Thickest muscular wall}", tex_template=my_template).scale(0.65), VGroup(Tex(r"\text{Pumps oxygenated blood}", tex_template=my_template), Tex(r"\text{to body}", tex_template=my_template)).arrange(DOWN, aligned_edge=LEFT, buff=0.15).scale(0.65), Tex(r"\text{High-pressure chamber}", tex_template=my_template).scale(0.65)
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        
        left_grp_1 = VGroup(title_1, bullets_grp_1).arrange(DOWN, aligned_edge=LEFT, buff=0.5)
        left_grp_1.move_to(LEFT * 3.5)
        
        # Arrow from text to image region
        arrow_1 = Arrow(
            start=left_grp_1.get_right() + RIGHT * 0.2,
            end=img_1.get_corner(DR),
            color=DesignTokens.YELLOW, buff=0.1, stroke_width=6
        )
        
        self.play(FadeIn(img_1), FadeIn(frame_1))
        self.play(Write(left_grp_1))
        self.play(GrowArrow(arrow_1))
        self.wait(4.0)
    

        # Scene 2: mcq_layout — draw 4 option boxes
        self._clear()

        opt_A_2_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=1.0).move_to(np.array([-3.2,  1.2, 0]))
        opt_A_2_letter = Tex(r"\text{A.}", tex_template=my_template)
        opt_A_2_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([-3.2,  1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(1.0)
        opt_A_2_text = Tex(r"\text{Tricuspid Valve}", tex_template=my_template)
        opt_A_2_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([-3.2,  1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(1.0)
        opt_A_2_grp = VGroup(opt_A_2_box, opt_A_2_letter, opt_A_2_text)
        self.play(FadeIn(opt_A_2_grp), run_time=0.3)

        opt_B_2_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=1.0).move_to(np.array([ 3.2,  1.2, 0]))
        opt_B_2_letter = Tex(r"\text{B.}", tex_template=my_template)
        opt_B_2_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([ 3.2,  1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(1.0)
        opt_B_2_text = Tex(r"\text{Mitral Valve}", tex_template=my_template)
        opt_B_2_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([ 3.2,  1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(1.0)
        opt_B_2_grp = VGroup(opt_B_2_box, opt_B_2_letter, opt_B_2_text)
        self.play(FadeIn(opt_B_2_grp), run_time=0.3)

        opt_C_2_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=1.0).move_to(np.array([-3.2, -1.2, 0]))
        opt_C_2_letter = Tex(r"\text{C.}", tex_template=my_template)
        opt_C_2_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([-3.2, -1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(1.0)
        opt_C_2_text = Tex(r"\text{Pulmonary Valve}", tex_template=my_template)
        opt_C_2_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([-3.2, -1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(1.0)
        opt_C_2_grp = VGroup(opt_C_2_box, opt_C_2_letter, opt_C_2_text)
        self.play(FadeIn(opt_C_2_grp), run_time=0.3)

        opt_D_2_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=1.0).move_to(np.array([ 3.2, -1.2, 0]))
        opt_D_2_letter = Tex(r"\text{D.}", tex_template=my_template)
        opt_D_2_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([ 3.2, -1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(1.0)
        opt_D_2_text = Tex(r"\text{Aortic Valve}", tex_template=my_template)
        opt_D_2_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([ 3.2, -1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(1.0)
        opt_D_2_grp = VGroup(opt_D_2_box, opt_D_2_letter, opt_D_2_text)
        self.play(FadeIn(opt_D_2_grp), run_time=0.3)
        self.wait(0.8)

        # Scene 3: option_arrow — highlight B
        box_pos_3 = np.array([ 3.2,  1.2, 0])
        # Continuity Guard: Phantom redraw with helper
        
        opt_B_3_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=0.3).move_to(box_pos_3)
        opt_B_3_letter = Tex(r"\text{B.}", tex_template=my_template)
        opt_B_3_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(box_pos_3 + np.array([-2.4, 0, 0])).set_opacity(0.3)
        opt_B_3_text = Tex(r"\text{-}", tex_template=my_template)
        opt_B_3_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(box_pos_3 + np.array([0.3, 0, 0])).set_opacity(0.3)
        opt_B_3_grp = VGroup(opt_B_3_box, opt_B_3_letter, opt_B_3_text)
        self.add(opt_B_3_grp)
        
        focus_ring_3 = RoundedRectangle(width=6.0, height=1.7, color=DesignTokens.YELLOW, stroke_width=4, corner_radius=0.15).move_to(box_pos_3)
        self.play(Indicate(focus_ring_3, color=DesignTokens.YELLOW, scale_factor=1.1), run_time=1.5)
        self.wait(1.5)


        # Scene 4: cross_out — ['A', 'C', 'D']

        # Continuity Guard: Phantom redraw with helper
        
        opt_A_4_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=0.3).move_to(np.array([-3.2,  1.2, 0]))
        opt_A_4_letter = Tex(r"\text{A.}", tex_template=my_template)
        opt_A_4_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([-3.2,  1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(0.3)
        opt_A_4_text = Tex(r"\text{-}", tex_template=my_template)
        opt_A_4_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([-3.2,  1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(0.3)
        opt_A_4_grp = VGroup(opt_A_4_box, opt_A_4_letter, opt_A_4_text)
        self.add(opt_A_4_grp)
        cross_4_0 = Cross(opt_A_4_grp, color=DesignTokens.RED, stroke_width=6)
        self.play(Create(cross_4_0), run_time=0.4)

        # Continuity Guard: Phantom redraw with helper
        
        opt_C_4_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=0.3).move_to(np.array([-3.2, -1.2, 0]))
        opt_C_4_letter = Tex(r"\text{C.}", tex_template=my_template)
        opt_C_4_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([-3.2, -1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(0.3)
        opt_C_4_text = Tex(r"\text{-}", tex_template=my_template)
        opt_C_4_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([-3.2, -1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(0.3)
        opt_C_4_grp = VGroup(opt_C_4_box, opt_C_4_letter, opt_C_4_text)
        self.add(opt_C_4_grp)
        cross_4_1 = Cross(opt_C_4_grp, color=DesignTokens.RED, stroke_width=6)
        self.play(Create(cross_4_1), run_time=0.4)

        # Continuity Guard: Phantom redraw with helper
        
        opt_D_4_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=0.3).move_to(np.array([ 3.2, -1.2, 0]))
        opt_D_4_letter = Tex(r"\text{D.}", tex_template=my_template)
        opt_D_4_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([ 3.2, -1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(0.3)
        opt_D_4_text = Tex(r"\text{-}", tex_template=my_template)
        opt_D_4_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([ 3.2, -1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(0.3)
        opt_D_4_grp = VGroup(opt_D_4_box, opt_D_4_letter, opt_D_4_text)
        self.add(opt_D_4_grp)
        cross_4_2 = Cross(opt_D_4_grp, color=DesignTokens.RED, stroke_width=6)
        self.play(Create(cross_4_2), run_time=0.4)
        self.wait(2.0)

        # Scene 5: answer_reveal — correct: B
        # Continuity Guard: Phantom redraw with helper
        
        opt_B_5_box = RoundedRectangle(width=5.8, height=1.5, corner_radius=0.15,
            color=DesignTokens.WHITE, stroke_width=2, stroke_opacity=0.3).move_to(np.array([ 3.2,  1.2, 0]))
        opt_B_5_letter = Tex(r"\text{B.}", tex_template=my_template)
        opt_B_5_letter.scale(0.85).set_color(DesignTokens.BLUE).move_to(np.array([ 3.2,  1.2, 0]) + np.array([-2.4, 0, 0])).set_opacity(0.3)
        opt_B_5_text = Tex(r"\text{-}", tex_template=my_template)
        opt_B_5_text.scale(0.65).set_color(DesignTokens.WHITE).move_to(np.array([ 3.2,  1.2, 0]) + np.array([0.3, 0, 0])).set_opacity(0.3)
        opt_B_5_grp = VGroup(opt_B_5_box, opt_B_5_letter, opt_B_5_text)
        self.add(opt_B_5_grp)
        
        highlight_5 = SurroundingRectangle(opt_B_5_grp, color=DesignTokens.GREEN, buff=0.08, stroke_width=5)
        tick_5 = Tex(r"$\checkmark$", tex_template=my_template).scale(1.4).set_color(DesignTokens.GREEN)
        tick_5.move_to(np.array([ 3.2,  1.2, 0]) + np.array([2.2, 0, 0]))
        self.play(GrowFromCenter(highlight_5), run_time=0.8)
        self.play(Write(tick_5))
        self.wait(4.0)

        self.wait(1)
