"""
Auto-generated Manim script for: Heart Anatomy (Grounded)
Generated by EaseToLearn template_renderer.py — DO NOT EDIT MANUALLY
"""

import numpy as np
from manim import *

# ── LaTeX Template ─────────────────────────────────────────────────────────────
my_template = TexTemplate()
my_template.add_to_preamble(r"\usepackage{amsmath}")
my_template.add_to_preamble(r"\usepackage{amssymb}")

# ── 3Blue1Brown High-Fidelity Design System ──────────────────────────────────
class DesignTokens:
    BLUE   = "#58ADFF"
    GREEN  = "#77DD77"
    YELLOW = "#FFFF66"
    RED    = "#FF6666"
    PURPLE = "#C57AFF"
    WHITE  = "#FFFFFF"
    GRAY   = "#888888"
    BLACK  = "#000000"
    MAX_WIDTH = 12.0
    TITLE_SIZE = 1.4
    BODY_SIZE = 0.8
    SUBTITLE_SIZE = 0.7

config.background_color = DesignTokens.BLACK
config.pixel_height = 1080
config.pixel_width  = 1920

class EaseToLearnScene(Scene):

    def _clear(self):
        """Fade out all mobjects safely."""
        fos = [FadeOut(m) for m in self.mobjects]
        if fos:
            self.play(*fos)

    def _clear_keep_image(self):
        """Fade out all mobjects except background ImageMobject."""
        fos = [FadeOut(m) for m in self.mobjects if not isinstance(m, ImageMobject)]
        if fos:
            self.play(*fos)

    def construct(self):
        # Industrial 3b1b Canvas: Absolute Black
        # DesignTokens are available as a global class in this script.
        self.camera.background_color = DesignTokens.BLACK

        # Scene 0: title_card
        title_0 = Tex(r"\text{Cardiovascular Anatomy}", tex_template=my_template)
        title_0.scale(DesignTokens.TITLE_SIZE).set_color(DesignTokens.YELLOW).move_to(UP * 0.5)
        if title_0.width > DesignTokens.MAX_WIDTH: title_0.set_width(DesignTokens.MAX_WIDTH)

        self.play(Write(title_0), run_time=0.45)
        subtitle_0 = Tex(r"\text{Vision-Grounded Arrow Test}", tex_template=my_template)
        subtitle_0.scale(DesignTokens.SUBTITLE_SIZE).set_color(DesignTokens.BLUE).next_to(title_0, DOWN, buff=0.4)
        self.play(FadeIn(subtitle_0), run_time=0.9)
        self.wait(2.1)
        self.play(FadeOut(title_0), FadeOut(subtitle_0))


        # Scene 1: annotated_image
        self._clear()
        img_1 = ImageMobject(r"/Users/apple/Desktop/easetolearn.videogeneration/scratch/internal_heart_anatomy_diagram.png").scale_to_fit_width(5.5).move_to(RIGHT * 3.2)
        frame_1 = SurroundingRectangle(img_1, color=BLUE_E, buff=0.08, stroke_width=3)
        
        # Left side: explanation
        title_1 = Tex(r"\text{The Left Ventricle}", tex_template=my_template).scale(0.9).set_color(DesignTokens.YELLOW)
        
        bullets_grp_1 = VGroup(
            Tex(r"\text{Thickest muscular wall}", tex_template=my_template).scale(0.65), Tex(r"\text{Pumps oxygenated blood}", tex_template=my_template).scale(0.65), Tex(r"\text{High-pressure chamber}", tex_template=my_template).scale(0.65)
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        
        left_grp_1 = VGroup(title_1, bullets_grp_1).arrange(DOWN, aligned_edge=LEFT, buff=0.5)
        left_grp_1.move_to(LEFT * 3.5)
        
        # Arrow from text to image landmark
        arrow_1 = Arrow(
            start=left_grp_1.get_right() + RIGHT * 0.2,
            end=np.array([3.475, -0.825, 0]),
            color=DesignTokens.YELLOW, buff=0.1, stroke_width=6
        )
        
        self.play(FadeIn(img_1), FadeIn(frame_1))
        self.play(Write(left_grp_1))
        self.play(GrowArrow(arrow_1))
        self.wait(4.0)
    
        self.wait(1)
