"""
Auto-generated Manim script for: Sync Test
Generated by EaseToLearn template_renderer.py — DO NOT EDIT MANUALLY
"""

import numpy as np
from manim import *

# ── LaTeX Template ─────────────────────────────────────────────────────────────
# Includes amssymb and amsmath for symbols like \checkmark and ullet
my_template = TexTemplate()
my_template.add_to_preamble(r"\usepackage{amsmath}")
my_template.add_to_preamble(r"\usepackage{amssymb}")

config.background_color = "#0d0d1a"  # deep dark background
config.pixel_height = 1080
config.pixel_width  = 1920

class EaseToLearnScene(Scene):

    def _clear(self):
        """Fade out all mobjects safely."""
        fos = [FadeOut(m) for m in self.mobjects]
        if fos:
            self.play(*fos)

    def _clear_keep_image(self):
        """Fade out all mobjects except background ImageMobject."""
        fos = [FadeOut(m) for m in self.mobjects if not isinstance(m, ImageMobject)]
        if fos:
            self.play(*fos)

    def construct(self):
        # Industrial 3b1b Canvas: Absolute Black
        self.camera.background_color = DesignTokens.BLACK

        # Scene 0: formula_display
        self._clear()
        formula_0 = MathTex(r"E=mc^2", tex_template=my_template).scale(1.2)
        formula_0.move_to(UP * 0.5)
        if formula_0.width > DesignTokens.MAX_WIDTH: formula_0.set_width(DesignTokens.MAX_WIDTH)

        label_0 = Tex(r"\\text{Einstein's Mass-Energy Equivalence}", tex_template=my_template)
        label_0.scale(DesignTokens.SUBTITLE_SIZE).set_color(DesignTokens.BLUE).next_to(formula_0, DOWN, buff=0.5)
        if label_0.width > 10: label_0.set_width(10)

        self.play(Write(formula_0), run_time=4.0)
        self.play(FadeIn(label_0), run_time=0.5)
        self.wait(5.5)
        self.play(FadeOut(formula_0), FadeOut(label_0))

        self.wait(1)
