"""
Auto-generated Manim script for: Edge Cases Test
Generated by EaseToLearn template_renderer.py — DO NOT EDIT MANUALLY
"""

import numpy as np
from manim import *

# ── LaTeX Template ─────────────────────────────────────────────────────────────
my_template = TexTemplate()
my_template.add_to_preamble(r"\usepackage{amsmath}")
my_template.add_to_preamble(r"\usepackage{amssymb}")

# ── 3Blue1Brown High-Fidelity Design System ──────────────────────────────────
class DesignTokens:
    BLUE   = "#58ADFF"
    GREEN  = "#77DD77"
    YELLOW = "#FFFF66"
    RED    = "#FF6666"
    PURPLE = "#C57AFF"
    WHITE  = "#FFFFFF"
    GRAY   = "#888888"
    BLACK  = "#000000"
    MAX_WIDTH = 12.0
    TITLE_SIZE = 1.4
    BODY_SIZE = 0.8
    SUBTITLE_SIZE = 0.7

config.background_color = DesignTokens.BLACK
config.pixel_height = 1080
config.pixel_width  = 1920

class EaseToLearnScene(Scene):

    def _clear(self):
        """Fade out all mobjects safely."""
        fos = [FadeOut(m) for m in self.mobjects]
        if fos:
            self.play(*fos)

    def _clear_keep_image(self):
        """Fade out all mobjects except background ImageMobject."""
        fos = [FadeOut(m) for m in self.mobjects if not isinstance(m, ImageMobject)]
        if fos:
            self.play(*fos)

    def construct(self):
        # Industrial 3b1b Canvas: Absolute Black
        # DesignTokens are available as a global class in this script.
        self.camera.background_color = DesignTokens.BLACK

        # Scene 0: formula_derivation
        self._clear()
        heading_0 = Tex(r"\text{Edge Case 1: Notation Change}", tex_template=my_template)
        heading_0.scale(0.9).set_color(DesignTokens.YELLOW).to_edge(UP, buff=0.5)
        self.play(Write(heading_0), run_time=1.0)
        formula_0_0 = MathTex(r"\frac{a}{b} = c", tex_template=my_template).scale(1.2).move_to(ORIGIN)
        if formula_0_0.width > DesignTokens.MAX_WIDTH: formula_0_0.set_width(DesignTokens.MAX_WIDTH)
        self.play(Write(formula_0_0), run_time=1.5)
        formula_0_1 = MathTex(r"a/b = c", tex_template=my_template).scale(1.2).move_to(ORIGIN)
        if formula_0_1.width > DesignTokens.MAX_WIDTH: formula_0_1.set_width(DesignTokens.MAX_WIDTH)
        self.play(TransformMatchingTex(formula_0_0, formula_0_1), run_time=1.5)
        self.wait(1.5)
        self._clear()

        # Scene 1: formula_derivation
        self._clear()
        heading_1 = Tex(r"\text{Edge Case 2: Variable Introduction}", tex_template=my_template)
        heading_1.scale(0.9).set_color(DesignTokens.YELLOW).to_edge(UP, buff=0.5)
        self.play(Write(heading_1), run_time=1.0)
        formula_1_0 = MathTex(r"x = 5", tex_template=my_template).scale(1.2).move_to(ORIGIN)
        if formula_1_0.width > DesignTokens.MAX_WIDTH: formula_1_0.set_width(DesignTokens.MAX_WIDTH)
        self.play(Write(formula_1_0), run_time=1.5)
        formula_1_1 = MathTex(r"x + y = 5 + y", tex_template=my_template).scale(1.2).move_to(ORIGIN)
        if formula_1_1.width > DesignTokens.MAX_WIDTH: formula_1_1.set_width(DesignTokens.MAX_WIDTH)
        self.play(TransformMatchingTex(formula_1_0, formula_1_1), run_time=1.5)
        self.wait(1.5)
        self._clear()

        # Scene 2: formula_derivation
        self._clear()
        heading_2 = Tex(r"\text{Edge Case 3: Fraction Simplification}", tex_template=my_template)
        heading_2.scale(0.9).set_color(DesignTokens.YELLOW).to_edge(UP, buff=0.5)
        self.play(Write(heading_2), run_time=1.0)
        formula_2_0 = MathTex(r"\frac{70}{120} = x", tex_template=my_template).scale(1.2).move_to(ORIGIN)
        if formula_2_0.width > DesignTokens.MAX_WIDTH: formula_2_0.set_width(DesignTokens.MAX_WIDTH)
        self.play(Write(formula_2_0), run_time=1.5)
        formula_2_1 = MathTex(r"0.583 = x", tex_template=my_template).scale(1.2).move_to(ORIGIN)
        if formula_2_1.width > DesignTokens.MAX_WIDTH: formula_2_1.set_width(DesignTokens.MAX_WIDTH)
        self.play(TransformMatchingTex(formula_2_0, formula_2_1), run_time=1.5)
        self.wait(1.5)
        self._clear()
        self.wait(1)
